import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "bootstrap/dist/css/bootstrap.min.css";
import Sidebar from "../ui/dashboard/SideBar/Sidebar";
import Navbar from "../ui/dashboard/navbar/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="w-[100%] flex flex-col">
          <div className="h-[80px]">
            <Navbar/>
          </div>
          <div className="flex">
            <div className="w-[300px] bg-white ">
              <Sidebar />
            </div>
            <div className="flex-[4] w-[100%] min-h-[100vh] bg-slate-200">
              {children}
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
